# IT a docker-compose file for start all palladium servises.
version: '2'
services:
  db:
    image: postgres
    volumes:
        - db-volume:/data/postgres
  api-server:
    build:
      context: https://github.com/flaminestone/palladium-api.git
    command: ["puma"]
    depends_on:
      - db
    volumes:
      - data-volume:/palladium-api/tmp/puma/socket/
    tty: true
  clientside-server:
    build:
      context: https://github.com/flaminestone/palladium-view.git
      args:
        - config={"host":"http://0.0.0.0"}
    command: ["service", "nginx", "start"]
    ports:
      - "80:80"
    volumes:
      - data-volume:/tmp/puma
volumes:
  db-volume:
  data-volume: {}
