# IT a docker-compose file for start all palladium servises.
version: '2'
services:
  db:
    image: postgres
    volumes:
        - db-volume:/data/postgres
  api-server:
    build:
      context: https://github.com/flaminestone/palladium-api.git
    command: ["puma"]
    depends_on:
      - db
    volumes:
      - apidata-volume:/palladium-api/tmp/puma/socket/
    tty: true
    environment:
      - RACK_ENV=production
  clientside-build:
    volumes:
      - ./dist/:/palladium-view/host_dist
    build:
      context: https://github.com/flaminestone/palladium-view.git
  nginx-server:
    build:
      context: .
    volumes:
      - apidata-volume:/palladium/api
      - ./dist/:/palladium/view/
    ports:
      - "80:80"
    tty: true
volumes:
  db-volume:
  apidata-volume: {}
