# IT a docker-compose file for start all palladium services.
version: '3'
services:
  db:
    image: postgres
    volumes:
        - db:/var/lib/postgresql/data
  api-server:
    build:
      context: https://github.com/flaminestone/palladium-api.git
    command: ["puma"]
    depends_on:
      - db
    volumes:
      - apidata:/palladium-api/tmp/puma/socket/
    tty: true
    environment:
      - RACK_ENV=production
  clientside-build:
    volumes:
      - ./dist/:/palladium-view/host_dist
    build:
      context: https://github.com/flaminestone/palladium-view.git
  nginx-server:
    build:
      context: .
    volumes:
      - apidata:/palladium/api
      - ./dist/:/palladium/view/
    ports:
      - "80:80"
    tty: true
volumes:
  db:
  apidata: {}
