# IT a docker-compose file for start all palladium servises.
# Ports 80, 8080 and 5432 must be free
version: '2'
services:
  db:
    image: postgres
  api-server:
    build:
      context: https://github.com/flaminestone/palladium-api.git
    command: ["puma"]
    depends_on:
      - db
    volumes:
      - datavolume:/palladium-api/tmp/puma/socket/
    tty: true
  clientside-server:
    build:
      context: https://github.com/flaminestone/palladium-view.git
    command: ["service", "nginx", "start"]
    ports:
      - "80:80"
    volumes:
      - datavolume:/tmp/puma
volumes:
  datavolume: {}
